<a href="https://colab.research.google.com/github/dipesh0078/Regression/blob/main/Gradient_descent(m_an_b).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
from sklearn.datasets import make_regression
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import train_test_split

In [2]:
X,y= make_regression(n_samples=100, n_features=1, n_informative=1, noise=20, n_targets=1, random_state=13)

In [3]:
X.flatten()

array([-0.71239066, -0.43714566, -0.45375238,  0.95283061,  0.23785784,
        0.86121137, -0.24332625,  0.18494595, -0.72099967, -0.42989708,
        2.01522083,  0.39724133,  0.20780005, -0.23242587, -0.76862702,
        0.45315861,  0.63988397,  0.3595323 , -1.61510796,  1.74924179,
       -0.78898902, -0.51196509, -0.92833523,  2.15038297, -0.2073497 ,
       -1.63909341, -0.33861825, -0.32212366, -0.48137142, -0.52316421,
        0.72196506,  0.76591105,  0.45348104, -1.26160595, -2.18711527,
       -1.18541881,  0.21745166,  1.33031692, -1.08718159,  0.56226171,
       -1.51284512, -0.00238903, -0.27813452,  0.45181234,  1.19070527,
        0.92234415,  0.81499544, -0.6209797 ,  0.9137407 ,  1.13833305,
        1.47868574, -0.65105648, -0.37591996, -0.77466003,  0.50113729,
        1.3501879 ,  0.72916547, -0.08165156, -0.85414295,  0.46565797,
       -0.04450308, -0.05753239,  1.89274222, -1.04537713,  0.56465429,
       -1.92415945, -0.76403397,  0.12730328, -0.02677165, -0.14

In [124]:
X_train, X_test, y_train,y_test=train_test_split(X,y, train_size=0.2, random_state=13)

In [125]:
b=0
m=0
lr=0.1
all_b=[]
all_cost=[]
all_m=[]
epochs=200

In [129]:
for i in range(epochs):
    slope_b = 0  # Reset gradient for b
    slope_m = 0  # Reset gradient for m
    cost = 0

    # Compute gradients and cost
    for j in range(X_train.shape[0]):
        error = y_train[j] - (m * X_train[j] + b)  # Prediction error
        slope_b += -2 * error  # Gradient for b
        slope_m += -2 * error * X_train[j]  # Gradient for m
        cost += error**2  # Accumulate cost

    # Update parameters
    b -= lr * slope_b / X_train.shape[0]  # Average gradient
    m -= lr * slope_m / X_train.shape[0]  # Average gradient///

    # Record values for visualization
    all_b.append(b)
    all_m.append(m)
    all_cost.append(cost / X_train.shape[0])  # Average cost per sample


In [130]:
m

array([24.94827839])

In [131]:
b

array([-3.90750811])

In [117]:
lr=SGDRegressor()

In [118]:
lr.fit(X_train,y_train)

SGDRegressor()

In [119]:
lr.coef_

array([24.83881062])

In [120]:
lr.score(X_test,y_test)

0.7104588278859023

In [121]:
lr.intercept_

array([-3.92606089])